# Generated by Django 4.2.4 on 2023-10-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Doctors_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=250)),
                ('specialization', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'doctors_profile',
            },
        ),
    ]
