# Generated by Django 4.2.6 on 2023-10-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_doctors_info',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
