# Generated by Django 4.2.6 on 2023-10-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_doctors_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_doctors_info',
            name='phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
